name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_software_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print Software Versions (Data Processing Level)
        run: |
          echo "Node.js Version:"
          node --version
          echo "Python Version:"
          python --version
          echo "Java Version:"
          java --version

  check_db_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print Database Version (Data Access Level)
        run: |
          echo "PostgreSQL Version:"
          psql --version
          echo "MySQL Version:"
          mysql --version

